### ISSUE TITLE
Cannot run npm run build/npm install truffle -g

### ISSUE THREAD

**Issue by Zorvaz** [HashLips/generative-art-node#109]
i have tried on mac and windows but in the end, I keep getting the same message i.e. cannot find the directory and it always refers to "layers/ball" but I have already changed the layers and there is no ball layer.[](url)

**Comment by magradze** [comment]
Error: ENOENT, No such file or directory 'C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update/layers/Mouths/MaunthWithThreeDent.png'
    at setSource (C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\node_modules\←[4mcanvas←[24m\lib\image.js:91:13)
    at Image.set (C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\node_modules\←[4mcanvas←[24m\lib\image.js:62:9)
    at C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\node_modules\←[4mcanvas←[24m\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\node_modules\←[4mcanvas←[24m\index.js:23:10)
    at C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\src\main.js:101:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\src\main.js:100:10)
    at C:\Users\User\Desktop\NFT Gen\hashlips_art_engine-1.0.0_update\src\main.js:161:29
    at Array.forEach (<anonymous>) {
  errno: ←[33m2←[39m,
  code: ←[32m'ENOENT'←[39m,
  path: ←[32m'C:\\Users\\User\\Desktop\\NFT Gen\\hashlips_art_engine-1.0.0_update/layers/Mouths/MaunthWithThreeDent.png'←[39m,
  syscall: ←[32m'fopen'←[39m
}
