### ISSUE TITLE
Message d'erreur 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by HaySiix** [HashLips/generative-art-node#142]
Bonsoir,
quand je veux lancer le programme j'ai un message d'erreur qui apparait 'ERR_DLOPEN_FAILED'. J'ai installé node.js, j'ai taper la commande npm install. Donc je ne sais pas de où sa provient.

PS C:\Users\doria\OneDrive\Bureau\generative-art-node-main> npm run build

> art_generator@1.0.0 build
> node index.js

node:internal/modules/cjs/loader:1179
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\doria\OneDrive\Bureau\generative-art-node-main\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1179:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\doria\OneDrive\Bureau\generative-art-node-main\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v17.3.1

**Comment by HaySiix** [comment]
PS C:\Users\doria\OneDrive\Bureau\generative-art-node-main> npm run build

> art_generator@1.0.0 build
> node index.js

node:internal/modules/cjs/loader:1179
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\doria\OneDrive\Bureau\generative-art-node-main\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1179:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\doria\OneDrive\Bureau\generative-art-node-main\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v17.3.1

**Comment by yahyamourad** [comment]
Same

**Comment by OctaneDDDDD** [comment]
same it happens when running the following command "npm run generate"
