### ISSUE TITLE
Getting NPM ERR on 'npm i' command

### ISSUE THREAD

**Issue by jakesanchezgo2019** [HashLips/generative-art-node#143]
My rig is Windows 10 32bit, using node.js 14.18.1 as explained on hashlips' video, already installed MS V C++ redistributions and the build tools + gtk+2.0 added on the path variable.

Still having issue once trying 'npm i' on terminal.

here's the details:

PS C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1> npm i

> canvas@2.8.0 install C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-win32-unknown-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.18.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-win32-unknown-ia32.tar.gz 
gyp ERR! find VS 
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.11.32106.194) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)        
gyp ERR! stack     at C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sboxm\\AppData\\Roaming\\nvm\\v14.18.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\sboxm\\Desktop\\Gawain\\nft\\hashlips_art_engine-1.1.2_patch_v1\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\sboxm\\Desktop\\Gawain\\nft\\hashlips_art_engine-1.1.2_patch_v1\\node_modules\\canvas\\build\\Release" "--napi_version=8" 
"--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83" "--msvs_version=2017"
gyp ERR! cwd C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Windows_NT 10.0.19044
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sboxm\\Desktop\\Gawain\\nft\\hashlips_art_engine-1.1.2_patch_v1\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas
node-pre-gyp ERR! node -v v14.18.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.6
node-pre-gyp ERR! not ok 
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\sboxm\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\sboxm\Desktop\Gawain\nft\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --msvs_version=2017' (1)
npm WARN hashlips_art_engine@1.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging 
output above.

I don't know if it's because I'm using x86 cpu or is it because the project was made under x64!??!?!?!?!?!

Hoping for other solutions! Thanks..

**Comment by HowRadOuyang** [comment]
Encountered the same error. Trying to look for the solution, too
