### ISSUE TITLE
Getting this error - error Failed at the art_generator@1.0.0 build script.

### ISSUE THREAD

**Issue by esboyles** [HashLips/generative-art-node#17]
Anyone have a fix for this? I validated and node, npm, etc are all installed correctly.

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle art_generator@1.0.0~prebuild: art_generator@1.0.0
6 info lifecycle art_generator@1.0.0~build: art_generator@1.0.0
7 verbose lifecycle art_generator@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle art_generator@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Eric\NFT_Gen2\generative-art-node\node_modules\.bin;C:\Users\Eric\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Eric\AppData\Local\Programs\Python\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\Eric\AppData\Local\Programs\Python\Python39;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files;C:\Winnt;C:\WINDOWS\System32\Wbem;C:\Winnt\System32;C:\Program Files (x86)\Nmap;C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Eric\AppData\Roaming\npm;C:\Users\Eric\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle art_generator@1.0.0~build: CWD: C:\Users\Eric\NFT_Gen2\generative-art-node
10 silly lifecycle art_generator@1.0.0~build: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle art_generator@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle art_generator@1.0.0~build: Failed to exec build script
13 verbose stack Error: art_generator@1.0.0 build: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid art_generator@1.0.0
15 verbose cwd C:\Users\Eric\NFT_Gen2\generative-art-node
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error art_generator@1.0.0 build: `node index.js`
22 error Exit status 1
23 error Failed at the art_generator@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by esboyles** [comment]
as an aside, when I execute node index.js I get this

  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'undefined/build'

**Comment by cfech** [comment]
was this fixed by an update that seems to have been made today?  The fact the path was undefined makes me think the working directory was not set which seems to be fixed now.

**Comment by cfech** [comment]
https://github.com/HashLips/generative-art-node/issues/10 

here is a similar error

**Comment by Rikhartgers** [comment]
It doesnt seem to be fixed I have the same problem with the build script.

**Comment by xddyyy** [comment]
try: npm --prefix (your directory) install 
after that: npm --prefix (your directory) run build
