### ISSUE TITLE
Build script issue (on Imac)

### ISSUE THREAD

**Issue by Rikhartgers** [HashLips/generative-art-node#24]
Hi guys I am quite new to code and it gives me this error. I did npm install and canvas and truffle. But nothing seems to work. Can someone help me out? The log is below v

0 info it worked if it ends with ok
1 verbose cli [ '/Users/rikhartgers/.nvm/versions/node/v11.5.0/bin/node',
1 verbose cli   '/Users/rikhartgers/.nvm/versions/node/v11.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v11.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle art_generator@1.0.0~prebuild: art_generator@1.0.0
6 info lifecycle art_generator@1.0.0~build: art_generator@1.0.0
7 verbose lifecycle art_generator@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle art_generator@1.0.0~build: PATH: /Users/rikhartgers/.nvm/versions/node/v11.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rikhartgers/Desktop/generative-art-node-main/node_modules/.bin:/Users/rikhartgers/.nvm/versions/node/v11.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/rikhartgers/.nvm/versions/node/v11.5.0/bin
9 verbose lifecycle art_generator@1.0.0~build: CWD: /Users/rikhartgers/Desktop/generative-art-node-main
10 silly lifecycle art_generator@1.0.0~build: Args: [ '-c', 'node index.js' ]
11 silly lifecycle art_generator@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle art_generator@1.0.0~build: Failed to exec build script
13 verbose stack Error: art_generator@1.0.0 build: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/rikhartgers/.nvm/versions/node/v11.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/rikhartgers/.nvm/versions/node/v11.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid art_generator@1.0.0
15 verbose cwd /Users/rikhartgers/Desktop/generative-art-node-main
16 verbose Darwin 20.3.0
17 verbose argv "/Users/rikhartgers/.nvm/versions/node/v11.5.0/bin/node" "/Users/rikhartgers/.nvm/versions/node/v11.5.0/bin/npm" "run" "build"
18 verbose node v11.5.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error art_generator@1.0.0 build: `node index.js`
22 error Exit status 1
23 error Failed at the art_generator@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by grantreighard** [comment]
Try `node index.js` to create images (default to 5) with the layers. `node index.js 10` will create 10.

**Comment by NikoTeresin** [comment]
i got the same problem on mac.
